<?php
/**
 * @file
 * 
 */

function news_aggregator_menu() {
  $items = array();
  $items['admin/news_aggregator/import'] = array(
    'title' => t('Import RSS'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('news_aggregator_form'),
    'access arguments' => array('access content'),
    'description' => t('My form'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Import form
 */
function news_aggregator_form($form, &$form_state) {
  $form['url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL'),
    '#default_value' => 'http://index.hu/24ora/rss',
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );

  return $form;

}



/**
 * Import form
 */
function news_aggregator_form_submit($form, &$form_state) {
  
  
  $countIx = 0;
 
$xml = new XMLReader();
$xml->open('/www/esn.dev/merged.xml');
 
while($xml->read() && $xml->name != 'prod')
{
  ;
}
 
while($xml->name == 'prod')
{
  $element = new SimpleXMLElement($xml->readOuterXML());
  
  $prod = array(
    'name' => strval($element->text->name),
    'price' => strval($element->price->buynow),
    'currency' => strval($element->price->attributes()->curr)
  );
  
  print_r($prod);
  print "\n";
  $countIx++;
  
  $xml->next('prod');
  unset($element);
}
 
print "Number of items=$countIx\n";
print "memory_get_usage() =" . memory_get_usage()/1024 . "kb\n";
print "memory_get_usage(true) =" . memory_get_usage(true)/1024 . "kb\n";
print "memory_get_peak_usage() =" . memory_get_peak_usage()/1024 . "kb\n";
print "memory_get_peak_usage(true) =" . memory_get_peak_usage(true)/1024 . "kb\n";
 
print "custom memory_get_process_usage() =" . memory_get_process_usage() . "kb\n";
 
 
$xml->close();


}
function memory_get_process_usage()
{
  $status = file_get_contents('/proc/' . getmypid() . '/status');
  
  $matchArr = array();
  preg_match_all('~^(VmRSS|VmSwap):\s*([0-9]+).*$~im', $status, $matchArr);
  
  if(!isset($matchArr[2][0]) || !isset($matchArr[2][1]))
  {
    return false;
  }
  
  return intval($matchArr[2][0]) + intval($matchArr[2][1]);
}